version: "3.7"

services:
  php8-fpm:
    container_name: php80-fpm-project16
    image: my-images/php80-fpm-alpine:0.1
    restart: always
    volumes:
      - /home/docker/projects/16_Laravel8_Api_VueJS_Spa:/usr/share/nginx/html # Docker toolbox + VirtualBox
      # - ../:/usr/share/nginx/html # Docker desktop + WSL2
    networks:
      - backEnd-network

  nginx:
    container_name: nginx-project16
    env_file: .env
    image: my-images/nginx118-alpine:0.1
    volumes:
      - /home/docker/projects/16_Laravel8_Api_VueJS_Spa:/usr/share/nginx/html # Docker toolbox + VirtualBox
      # - ../:/usr/share/nginx/html # Docker desktop + WSL2
    ports:
      - ${PROJECT_PORT}:${PORT}
    networks:
      - backEnd-network
    links:
      - php8-fpm

  postgresql:
    container_name: postgresql-project16
    image: my-images/postgresql13-alpine:0.1
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_SCHEMA=${POSTGRES_SCHEMA}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - backEnd-network

networks:
  backEnd-network:
    driver: bridge

volumes:
  pgdata:
    name: "pgdata_16_Laravel8_Api_VueJS_Spa" ## cambiar por pgdata_<nombre-carpeta-proyecto>
    external: false
